{
 "title": "UPS Stats",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Load (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ups_pct_load", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Load (watts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ups_watt_load", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Utility (Volts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "ups_utility_volts", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Battery capacity (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "ups_battery_capacity", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "State (line/battery)",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ups_state{ups_state=\"line\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time left (minutes)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_time_left", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}